name: mlkit_scanner
description: A Flutter plugin to detect barcodes, text, faces, and objects using Google MLKit API for iOS and Android
version: 0.1.0
author: ООО "ДНС Технологии"
homepage: https://www.dns-tech.ru/

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: com.dns_technologies.mlkit_scanner
        pluginClass: MlkitScannerPlugin
      ios:
        pluginClass: MlkitScannerPlugin


